import "./ArticleFactGenerator.scss"
import React, {useEffect, useState} from 'react'
import $ from 'jquery'
import Article from "/src/components/articles/base/Article.jsx"
import StandardButton from "/src/components/buttons/StandardButton.jsx"

/**
 * Fetches and displays a random fact using jQuery, with a button to get a new one.
 * @param {ArticleDataWrapper} dataWrapper
 * @param {Number} id
 * @return {JSX.Element}
 * @constructor
 */
function ArticleFactGenerator({ dataWrapper, id }) {
    const [fact, setFact] = useState(null)
    const [loading, setLoading] = useState(false)

    const fetchFact = () => {
        setLoading(true)
        $.get("https://uselessfacts.jsph.pl/api/v2/facts/random?language=en",
            function(result) {
                console.log("From Useless Facts API: " + JSON.stringify(result))
                if (!result || !result.text) {
                    setLoading(false)
                    return
                }
                setFact(result.text)
                setLoading(false)
            }
        ).fail(function() {
            setLoading(false)
        })
    }

    useEffect(() => {
        // fetch a fact immediately on load
        fetchFact()
    }, [])

    return (
        <Article id={dataWrapper.uniqueId}
                 type={Article.Types.SPACING_DEFAULT}
                 dataWrapper={dataWrapper}
                 className={`article-fact-generator`}>
            <div className={`article-fact-generator-content text-3`}>
                <i className={`fa-solid fa-lightbulb article-fact-generator-icon`}/>

                {fact ? (
                    <p className={`article-fact-generator-text`}>{fact}</p>
                ) : (
                    <p className={`article-fact-generator-text`}>Loading fact...</p>
                )}

                <StandardButton label={loading ? "Loading..." : "SHOW ME ANOTHER FACT"}
                                onClick={fetchFact}
                                status={loading ? StandardButton.Status.DISABLED : StandardButton.Status.ENABLED}
                                size={StandardButton.Size.DEFAULT}/>

                <p className={`article-fact-generator-disclaimer text-2 opacity-75`}>
                    <em>*Facts provided by Useless Facts API. Content is generated by a third-party service and I am not responsible for it.</em>
                </p>
            </div>
        </Article>
    )
}

export default ArticleFactGenerator