import "./ArticleJoke.scss"
import React, {useEffect, useState} from 'react'
import $ from 'jquery'
import Article from "/src/components/articles/base/Article.jsx"

/**
 * Fetches and displays a programming joke from JokeAPI every minute using jQuery.
 * @param {ArticleDataWrapper} dataWrapper
 * @param {Number} id
 * @return {JSX.Element}
 * @constructor
 */
function ArticleJoke({dataWrapper, id}) {
	const [joke, setJoke] = useState(null)

	const fetchJoke = () => {
		$.get("https://v2.jokeapi.dev/joke/Any?type=single",
			function(result) {
				console.log("From jokeAPI: " + JSON.stringify(result))
				if (!result || !result.joke) return
				setJoke(result.joke)
			}
		)
	}

	useEffect(() => {
		// fetch immediately on load
		fetchJoke()

		// refresh every minute
		const interval = setInterval(fetchJoke, 60000)

		// cleaning interval on unmount
		return () => clearInterval(interval)
	}, [])

	return (
		<Article id={dataWrapper.uniqueId}
				 type={Article.Types.SPACING_DEFAULT}
				 dataWrapper={dataWrapper}
				 className={`article-joke`}>
			<div className={`article-joke-content text-3`}>
				<i className={`fa-solid fa-face-laugh article-joke-icon`}/>
				{joke ? (
					<p className={`article-joke-text`}>{joke}</p>
				) : (
					<p className={`article-joke-text`}>Loading joke...</p>
				)}
				<p className={`article-joke-disclaimer text-2 opacity-75`}>
					<em>*Joke provided by JokeAPI. Content is generated by a third-party service and I am not responsible for it.</em>
				</p>
			</div>
		</Article>
	)
}

export default ArticleJoke