import "./ArticleWeather.scss"
import React, {useEffect, useState} from 'react'
import Article from "/src/components/articles/base/Article.jsx"

/**
 * Maps Weatherbit icon codes to Meteocons animated SVG icon names.
 * @param {String} code - Weatherbit icon code
 * @return {String} - Meteocons icon name
 */
function mapWeatherbitToMeteocons(code) {
	const isDay = code.endsWith('d')
	const base = code.slice(0, -1)

	const mapping = {
		c01: isDay ? 'clear-day' : 'clear-night',
		c02: isDay ? 'partly-cloudy-day' : 'partly-cloudy-night',
		c03: 'cloudy',
        c04: 'overcast',
        a01: 'mist',
        a02: 'fog',
        a03: 'haze',
        a04: 'smoke',
        a05: 'dust',
        a06: 'haze',
        r01: 'rain',
        r02: 'rain',
        r03: 'rain',
        r04: 'drizzle',
        r05: 'sleet',
        r06: 'sleet',
        s01: 'snow',
        s02: 'snow',
        s03: 'snow',
        s04: 'sleet',
        s05: 'snow',
        s06: 'snow',
        t01: 'thunderstorms-rain',
        t02: 'thunderstorms-rain',
        t03: 'thunderstorms-rain',
        t04: 'thunderstorms',
        t05: 'thunderstorms-rain',
        u00: 'not-available'
	}
	return mapping[base] || 'not-available'
}

/**
 * Fetches and displays current weather based on the user's location using Weatherbit API.
 * @param {ArticleDataWrapper} dataWrapper
 * @param {Number} id
 * @return {JSX.Element}
 * @constructor
 */
function ArticleWeather({dataWrapper, id}) {
	const [weather, setWeather] = useState(null)
	const [error, setError] = useState(null)

	const apiKey = import.meta.env.VITE_WEATHERBIT_API_KEY

	const fetchWeather = (lat, lon) => {
		fetch(`https://api.weatherbit.io/v2.0/current?lat=${lat}&lon=${lon}&key=${apiKey}&units=I`)
			.then(response => response.json())
			.then(result => {
				if (!result || !result.data || !result.data[0]) {
					setError("Unable to load weather data.")
					return
				}
				setWeather(result.data[0])
			})
			.catch(() => setError("Unable to load weather data."))
	}

	useEffect(() => {
		if (!navigator.geolocation) {
			setError("Geolocation is not supported by your browser.")
			return
		}

		navigator.geolocation.getCurrentPosition(
			(position) => {
				fetchWeather(position.coords.latitude, position.coords.longitude)
			},
			() => {
				setError("Location access denied. Unable to show local weather.")
			}
		)
	}, [])

	return (
		<Article id={dataWrapper.uniqueId}
				 type={Article.Types.SPACING_DEFAULT}
				 dataWrapper={dataWrapper}
				 className={`article-weather`}>
			<div className={`article-weather-content text-3`}>
				{error && (
					<p className={`article-weather-error`}>{error}</p>
				)}

				{!error && !weather && (
					<p className={`article-weather-loading`}>Loading weather...</p>
				)}

				{weather && (
					<div className={`article-weather-display`}>
						<img className={`article-weather-icon`}
							 src={`https://cdn.meteocons.com/3.0.0-next.10/svg/fill/${mapWeatherbitToMeteocons(weather.weather.icon)}.svg`}
							 alt={weather.weather.description}/>
						<div className={`article-weather-info`}>
							<p className={`article-weather-location`}>{weather.city_name}, {weather.state_code}, {weather.country_code}</p>
							<p className={`article-weather-temp`}>{Math.round(weather.temp)}°F</p>
							<p className={`article-weather-description`}>{weather.weather.description}</p>
						</div>
					</div>
				)}

				<p className={`article-weather-disclaimer text-2 opacity-75`}>
					<em>*Weather data provided by Weatherbit. Icons by Meteocons. Content is generated by a third-party service and I am not responsible for it.</em>
				</p>
			</div>
		</Article>
	)
}

export default ArticleWeather